apiVersion: v1 # version of k8s
kind: Pod  # we can write other service kind like deployment, service, config map, stateful stats
metadata: # gives identity to our pod
  name: my-pod
  labels:
    app: catalog
spec: # what the pod will run
  containers:  # list item, because in a pod, we can run 1 or more containers
    - name: catalog
      image: "267673636159.dkr.ecr.us-east-2.amazonaws.com/goapp"
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
      resources:
        limits:
          cpu: "200m"
          memory: "256Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"
      readinessProbe:
        httpGet:
          path: /
          port: 80